# Generated by Django 5.2.9 on 2025-12-08 16:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=15)),
                ('account_type', models.CharField(choices=[('current', 'Current'), ('savings', 'Savings'), ('cc', 'Cash Credit'), ('od', 'Overdraft')], default='current', max_length=20)),
                ('statement_format', models.CharField(choices=[('auto', 'Auto Detect'), ('sbi', 'SBI'), ('hdfc', 'HDFC Bank'), ('icici', 'ICICI Bank'), ('axis', 'Axis Bank'), ('kotak', 'Kotak Mahindra'), ('pnb', 'Punjab National Bank'), ('bob', 'Bank of Baroda'), ('canara', 'Canara Bank'), ('union', 'Union Bank'), ('idbi', 'IDBI Bank'), ('yes', 'Yes Bank'), ('indusind', 'IndusInd Bank'), ('federal', 'Federal Bank'), ('rbl', 'RBL Bank'), ('generic', 'Generic Format')], default='auto', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='companies.company')),
                ('tally_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.ledger')),
            ],
            options={
                'unique_together': {('company', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bank_statements/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'xlsx', 'xls', 'csv'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.IntegerField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('parsed', 'Parsed'), ('mapped', 'Mapped'), ('approved', 'Approved'), ('synced', 'Synced'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('processing_started', models.DateTimeField(blank=True, null=True)),
                ('processing_completed', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('total_transactions', models.IntegerField(default=0)),
                ('mapped_transactions', models.IntegerField(default=0)),
                ('approved_transactions', models.IntegerField(default=0)),
                ('synced_transactions', models.IntegerField(default=0)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_statements', to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='bank_statements.bankaccount')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParsedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=20)),
                ('cheque_number', models.CharField(blank=True, max_length=20)),
                ('confidence_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('auto_mapped', 'Auto Mapped'), ('manually_mapped', 'Manually Mapped'), ('approved', 'Approved'), ('voucher_created', 'Voucher Created'), ('synced', 'Synced'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('mapped_at', models.DateTimeField(blank=True, null=True)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mapped_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapped_transactions', to='companies.ledger')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank_statements.bankstatement')),
                ('suggested_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_transactions', to='companies.ledger')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.voucher')),
            ],
        ),
    ]
