# Generated by Django 5.2.9 on 2025-12-08 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('payment', 'Payment'), ('receipt', 'Receipt'), ('journal', 'Journal'), ('contra', 'Contra'), ('sales', 'Sales'), ('purchase', 'Purchase'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('payroll', 'Payroll')], max_length=20)),
                ('voucher_number', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('narration', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('queued', 'Queued'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('tally_master_id', models.CharField(blank=True, max_length=100)),
                ('tally_guid', models.CharField(blank=True, max_length=100)),
                ('sync_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_completed_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('sync_attempts', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('bank_statement', 'Bank Statement'), ('invoice_ocr', 'Invoice OCR'), ('manual', 'Manual'), ('import', 'Import'), ('api', 'API'), ('payroll', 'Payroll')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vouchers', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('party_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_vouchers', to='companies.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_debit', models.BooleanField(default=True)),
                ('bill_number', models.CharField(blank=True, max_length=50)),
                ('bill_type', models.CharField(blank=True, max_length=20)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.ledger')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='vouchers.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('request_xml', models.TextField(blank=True)),
                ('response_xml', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('connector_id', models.CharField(blank=True, max_length=100)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='vouchers.voucher')),
            ],
        ),
    ]
