# Generated by Django 5.2.9 on 2025-12-10 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='gst_details',
            field=models.JSONField(blank=True, default=dict, help_text='Stores cgst, sgst, igst, cess amounts'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='party_name',
            field=models.CharField(blank=True, help_text='Raw party name from import', max_length=255),
        ),
        migrations.AddField(
            model_name='voucher',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('error', 'Error')], default='unverified', max_length=20),
        ),
        migrations.CreateModel(
            name='VoucherSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('journal', 'Journal'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('contra', 'Contra')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_settings', to='companies.company')),
                ('default_cess_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaults_as_cess', to='companies.ledger')),
                ('default_cgst_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaults_as_cgst', to='companies.ledger')),
                ('default_igst_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaults_as_igst', to='companies.ledger')),
                ('default_purchase_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaults_as_purchase', to='companies.ledger')),
                ('default_sales_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaults_as_sales', to='companies.ledger')),
                ('default_sgst_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaults_as_sgst', to='companies.ledger')),
            ],
            options={
                'unique_together': {('company', 'transaction_type')},
            },
        ),
    ]
