# Generated by Django 5.2.9 on 2025-12-10 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_stockitem'),
        ('vouchers', '0002_voucher_gst_details_voucher_party_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='invoice_type',
            field=models.CharField(choices=[('accounting', 'Accounting Invoice'), ('item', 'Item Invoice')], default='accounting', max_length=20),
        ),
        migrations.CreateModel(
            name='SalesImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('with_item', 'With Item (Item Invoice)'), ('without_item', 'Without Item (Accounting Invoice)')], default='without_item', max_length=20)),
                ('voucher_type', models.CharField(default='sales', max_length=20)),
                ('original_file', models.FileField(upload_to='sales_imports/')),
                ('original_filename', models.CharField(max_length=255)),
                ('detected_columns', models.JSONField(blank=True, default=list)),
                ('sample_data', models.JSONField(blank=True, default=list)),
                ('total_rows', models.IntegerField(default=0)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('gst_config', models.JSONField(blank=True, default=dict)),
                ('ledger_mapping', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('uploaded', 'File Uploaded'), ('columns_detected', 'Columns Detected'), ('field_mapped', 'Fields Mapped'), ('gst_configured', 'GST Configured'), ('ledger_mapped', 'Ledgers Mapped'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('valid_rows', models.IntegerField(default=0)),
                ('warning_rows', models.IntegerField(default=0)),
                ('error_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('synced_rows', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_imports', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.stockitem')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vouchers.voucher')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SalesImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField(default=dict)),
                ('mapped_data', models.JSONField(blank=True, default=dict)),
                ('stock_items_data', models.JSONField(blank=True, default=list)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending Validation'), ('valid', 'Valid'), ('warning', 'Warning'), ('error', 'Error'), ('processed', 'Processed'), ('synced', 'Synced to Tally')], default='pending', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('party_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows_as_party', to='companies.ledger')),
                ('sales_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='vouchers.salesimport')),
                ('sales_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows_as_sales', to='companies.ledger')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='vouchers.voucher')),
            ],
            options={
                'ordering': ['row_number'],
                'unique_together': {('sales_import', 'row_number')},
            },
        ),
    ]
