# Generated by Django 5.2.9 on 2025-12-08 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('machine_name', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('tally_host', models.CharField(default='localhost', max_length=100)),
                ('tally_port', models.IntegerField(default=9000)),
                ('tally_company_name', models.CharField(blank=True, max_length=200)),
                ('api_key', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('disconnected', 'Disconnected')], default='inactive', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('connector_version', models.CharField(blank=True, max_length=20)),
                ('tally_version', models.CharField(blank=True, max_length=20)),
                ('total_operations', models.IntegerField(default=0)),
                ('successful_operations', models.IntegerField(default=0)),
                ('failed_operations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('create_voucher', 'Create Voucher'), ('update_voucher', 'Update Voucher'), ('delete_voucher', 'Delete Voucher'), ('sync_ledgers', 'Sync Ledgers'), ('sync_masters', 'Sync Masters'), ('export_report', 'Export Report')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=2)),
                ('request_data', models.JSONField(default=dict)),
                ('request_xml', models.TextField(blank=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('response_xml', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='tally_connector.desktopconnector')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='TallyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_type', models.CharField(choices=[('ledger', 'Ledger'), ('group', 'Group'), ('cost_center', 'Cost Center'), ('voucher_type', 'Voucher Type'), ('stock_item', 'Stock Item')], max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('tally_guid', models.CharField(blank=True, max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_masters', to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'master_type', 'name')},
            },
        ),
    ]
