# Generated by Django 5.2.9 on 2025-12-08 16:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GSTIN', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('pan', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')])),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('state_code', models.CharField(blank=True, max_length=2)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('tally_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('tally_connected', models.BooleanField(default=False)),
                ('last_tally_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tally_guid', models.CharField(blank=True, max_length=100)),
                ('parent_group', models.CharField(blank=True, max_length=200)),
                ('ledger_group', models.CharField(choices=[('bank_accounts', 'Bank Accounts'), ('cash_in_hand', 'Cash-in-Hand'), ('sundry_debtors', 'Sundry Debtors'), ('sundry_creditors', 'Sundry Creditors'), ('duties_taxes', 'Duties & Taxes'), ('direct_expenses', 'Direct Expenses'), ('indirect_expenses', 'Indirect Expenses'), ('direct_income', 'Direct Income'), ('indirect_income', 'Indirect Income'), ('fixed_assets', 'Fixed Assets'), ('capital_account', 'Capital Account'), ('other', 'Other')], default='other', max_length=50)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('gst_registration_type', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=15)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_debit', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_from_tally', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LedgerMappingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=200)),
                ('pattern_type', models.CharField(choices=[('contains', 'Contains'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('exact', 'Exact Match'), ('regex', 'Regex')], default='contains', max_length=20)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('both', 'Both')], default='both', max_length=10)),
                ('priority', models.IntegerField(default=0)),
                ('times_used', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_rules', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.ledger')),
            ],
        ),
    ]
