# Generated by Django 5.2.9 on 2025-12-08 16:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='invoices/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.IntegerField()),
                ('invoice_type', models.CharField(choices=[('purchase', 'Purchase Invoice'), ('sales', 'Sales Invoice'), ('expense', 'Expense Invoice')], default='purchase', max_length=20)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('vendor_gstin', models.CharField(blank=True, max_length=15)),
                ('vendor_address', models.TextField(blank=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ocr_provider', models.CharField(blank=True, max_length=20)),
                ('ocr_confidence', models.FloatField(default=0)),
                ('ocr_raw_text', models.TextField(blank=True)),
                ('ocr_extracted_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing OCR'), ('extracted', 'Data Extracted'), ('validated', 'Validated'), ('approved', 'Approved'), ('voucher_created', 'Voucher Created'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_invoices', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='companies.company')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice')),
                ('mapped_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapped_invoices', to='companies.ledger')),
                ('suggested_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_invoices', to='companies.ledger')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_invoices', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('ocr_value', models.TextField()),
                ('corrected_value', models.TextField()),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='invoices.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('hsn_code', models.CharField(blank=True, max_length=8)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('confidence_score', models.FloatField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoice')),
            ],
        ),
    ]
